### ISSUE TITLE
JS error on mobile menu button

### ISSUE THREAD

**Issue by selfagency** [holger1411/understrap-child#46]
When I try clicking on the hamburger menu in mobile view in any browser, I get the following JS error:

```
Uncaught Error: Collapse is transitioning
    at a.show (child-theme.min.js?ver=0.2.2:2)
    at a.toggle (child-theme.min.js?ver=0.2.2:2)
    at HTMLDivElement.<anonymous> (child-theme.min.js?ver=0.2.2:2)
    at Function.each (jquery.js?ver=1.12.4:2)
    at jQuery.fn.init.each (jquery.js?ver=1.12.4:2)
    at jQuery.fn.init.a._jQueryInterface [as collapse] (child-theme.min.js?ver=0.2.2:2)
    at HTMLButtonElement.<anonymous> (child-theme.min.js?ver=0.2.2:2)
    at HTMLDocument.dispatch (jquery.js?ver=1.12.4:3)
    at HTMLDocument.r.handle (jquery.js?ver=1.12.4:3)
```

**Comment by holger1411** [comment]
Hi!
I don´t get any error message (in my Chrome or FF debug console)here:
https://understrap.com/understrap/

Where do you get this error message (exactly)?

**Comment by selfagency** [comment]
http://www.gefilteria.com/

**Comment by selfagency** [comment]
still an issue in a production env for which i could use help. i paid for understrap via gumroad.

**Comment by holger1411** [comment]
Thanks for donating to the open source project UnderStrap.
But that did not include any custom support for commercial projects.

So I can give you just some generel hints/questions to narrow it down and to debug this:

- Did the problem still appears if you disable the child theme and if you use the pure uneditited UnderStrap parent theme?

- Disable all plugins, including any cahcing plugins and clear all caches. Does it still exists?

**Comment by selfagency** [comment]
no, the problem does not persist if i use the parent theme.
yes, the problem persists on the child theme if i disable all active plugins.

```
child-theme.min.js?ver=0.2.2:2 Uncaught Error: Collapse is transitioning
    at a.show (child-theme.min.js?ver=0.2.2:2)
    at a.toggle (child-theme.min.js?ver=0.2.2:2)
    at HTMLDivElement.<anonymous> (child-theme.min.js?ver=0.2.2:2)
    at Function.each (jquery.js?ver=1.12.4:2)
    at jQuery.fn.init.each (jquery.js?ver=1.12.4:2)
    at jQuery.fn.init.a._jQueryInterface [as collapse] (child-theme.min.js?ver=0.2.2:2)
    at HTMLButtonElement.<anonymous> (child-theme.min.js?ver=0.2.2:2)
    at HTMLDocument.dispatch (jquery.js?ver=1.12.4:3)
    at HTMLDocument.r.handle (jquery.js?ver=1.12.4:3)
```

**Comment by selfagency** [comment]
please please help me

**Comment by selfagency** [comment]
@holger1411 this is apparently a known bug in bootstrap that has been fixed in the next release, however, i can't really wait that long b/c my site is already in production. any chance you can integrate the fix?

https://github.com/twbs/bootstrap/pull/21743

**Comment by holger1411** [comment]
Sorry for my late reply.

The problem is that I can´t reproduce the probleme here with UnderStrap or the UnderStrap default child.
As you report it it only appears on your own customized child theme.
So it might be that problem is caused by the certain selection of Bootstrap components and elements you use on your custom version or it is caused by the customizations itself or another wired combination of things.

But because of that I can´t pull in some files and there dependencies from the bleeding-edge, pre-alpha 7 version into alpha 6 of bootstrap.
That could fix your problem (maybe), but there is a 95%+ chance that it caused other bugs. And that will effect thousands of UnderStrap installation. 

Using a alpha version in production is already highly risky, but mixing it with pre-alpha code is always a bad idea. Especially if it effects all active UnderStrap installations at once. So I can´t do that.

The good thing is open source did not just mean free of charge, it also means you are free to edit it by yourself.
So you could download the "not-yet-released" Alpha 7 version of Bootstrap, drop the bootstrap.js (https://github.com/twbs/bootstrap/tree/v4-dev/dist/js) file into your /src/js/bootstrap4/ folder, run `npm scripts` to compile it and test it on your own local/staging system.

Maybe you have to pull in the scss files to and recompile your css, too.

Feel free to report it if fixes your problem or not (could help others).

**Comment by selfagency** [comment]
you mean `grunt scripts` yeah? i replaced the alpha 6 package with https://github.com/twbs/bootstrap.git#v4-dev and ran `grunt scripts` and the error persists unfortunately.

**Comment by holger1411** [comment]
No, sorry `gulp scripts`, not grunt nor npm

**Comment by selfagency** [comment]
I was able to resolve this issue by removing `hidden-md-down` from `navbar-menu`.
