### ISSUE TITLE
thunkFunction error message

### ISSUE THREAD

**Issue by AlanaFarkas** [holger1411/understrap-child#63]
Hello,

I'm developing a new site using your child theme (the second site I've developed using your child theme) and get an unfamiliar error in the console when running `gulp watch`. There isn't a lot about this when I google and the one tip I did see on Stack Overflow did not work for me. I am able to hit ctrl + c to cancel out and run `gulp watch` again to render my new sass changes but it's annoying and slows things down. Can anyone help me fix this? Thanks in advance!

Screenshot below:

![screen shot 2017-05-31 at 4 29 26 pm](https://cloud.githubusercontent.com/assets/15007255/26652573/5af6971a-461e-11e7-9d85-7dd31ea0b227.png)

**Comment by aaronditto** [comment]
You can fix the thunk error using the method described here under this Understraps (Parent Theme) Issues topic:  https://github.com/holger1411/understrap/issues/330

This fixed it for me, but overall this child theme 0.3.2 is still not working well. I can't get my child-theme-min.css to update when using gulp watch, gulp watch-bs or gulp sass. 

I ended up reverting to Understraps 0.5.7 and Understraps Child 0.2.2. While it's a little slower due to cssnano  - at least it works properly.

**Comment by AlanaFarkas** [comment]
Thanks @aaronditto that fixed the issue for me -- sorry you're having trouble with this child theme. I'm using 0.3.2 and so far so good now that you helped me with the thunk error.
