### ISSUE TITLE
child-theme.css not overriding the parent theme

### ISSUE THREAD

**Issue by tellstevens** [holger1411/understrap-child#70]
I'm using CodeKit and compiling child-theme.scss -> css/child-theme.css. I've confirmed that my variables and my _child_theme.scss are compiling all the way back to child-theme.css but I'm not seeing my changes. 

Physical changes like removing sidebars and adding a div, etc are all showing up on the front end but the css just doesn't seem to be changing. Any ideas what is going on? 
![image](https://user-images.githubusercontent.com/10147938/27408586-085bd994-56a3-11e7-827c-23fac662cd5a.png)
Here's an example of my css but my theme is showing the default yellow of the child theme.

**Comment by holger1411** [comment]
By default the theme use the minified child-theme.min.css file.
If you just compile the scss to css via a third party compiler you will not see any changes. The theme uses the "old" min.css file instead of the "new" .css file.

By default you should run the gulp `watch task` (to constantly watch out for changes on scss file and compiling and minifing the files) or `gulp styles` to compile and minify em once.

If you don´t want to work with Gulp you can change the .css file path here:
https://github.com/holger1411/understrap/blob/master/inc/enqueue.php#L15
to theme.css instead of theme.min.css
Or you can use CodeKit to minify the file (don´t really know CodeKit but as far as I know it supports minify and uglify).

**Comment by tellstevens** [comment]
I figured it was something like that. My other issue was when I compiled it to minify it was overwriting everything in the file. I was able to just put the child-theme.min.css at the top of my scss file so it's there when it compiles and now it works. Thanks for the direction.
